environment                         = "Development"
vpc_name                            = "Bamaluz VPC"
vpc_enable_dns_hostnames            = true
vpc_enable_dns_support              = true
primary_subnet_name                 = "Public"
secondary_subnet_name               = "Private"
backend_subnet_name                 = "Backend"
vpc_instance_tenancy                = "default"
vpc_primary_public_ip_on_lauch      = true
vpc_secondary_public_ip_on_lauch    = false
vpc_cidr                            = "10.40.0.0/16"
sub_azs                             = ["eu-west-2a","eu-west-2b","eu-west-2c"]
public_subnets                      = ["10.40.1.0/24","10.40.2.0/24","10.40.3.0/24"]
private_subnets                     = ["10.40.4.0/24","10.40.5.0/24","10.40.6.0/24"]
backend_subnets                     = ["10.40.7.0/24","10.40.8.0/24","10.40.9.0/24"]
vpc_tags                 = {     
    Name = "Bamaluz VPC"
    Description = "Automation Services"
}
